-- initial songs
INSERT INTO SONG(id,title,artist,album,year) VALUES (1,'dobrown','Lucy Parsons','Marion Marshall Islands',1973);
INSERT INTO SONG(id,title,artist,album,year) VALUES (2,'consecteturbrown','Jennings Guerra','Kidder Nebraska',1966);
INSERT INTO SONG(id,title,artist,album,year) VALUES (3,'eubrown','Hallie Hopkins','Sparkill Georgia',2000);
INSERT INTO SONG(id,title,artist,album,year) VALUES (4,'voluptateblue','Ida Callahan','Alderpoint Indiana',1961);
INSERT INTO SONG(id,title,artist,album,year) VALUES (5,'aliquipgreen','Nadine Mooney','Statenville North Carolina',1976);
INSERT INTO SONG(id,title,artist,album,year) VALUES (6,'eabrown','Mcmahon Petty','Biddle Massachusetts',1971);
INSERT INTO SONG(id,title,artist,album,year) VALUES (7,'culpabrown','Becky Barber','Katonah Virginia',1987);
INSERT INTO SONG(id,title,artist,album,year) VALUES (8,'suntblue','Yvette Hoover','Tonopah New Mexico',1979);
INSERT INTO SONG(id,title,artist,album,year) VALUES (9,'dolorebrown','Guadalupe Nieves','Thomasville California',2011);
INSERT INTO SONG(id,title,artist,album,year) VALUES (10,'sitbrown','Alice Glover','Zortman Oklahoma',2015);
INSERT INTO SONG(id,title,artist,album,year) VALUES (11,'voluptategreen','Esmeralda Armstrong','Maybell Washington',1971);
INSERT INTO SONG(id,title,artist,album,year) VALUES (12,'esseblue','Franklin Reid','Sandston Montana',1965);
INSERT INTO SONG(id,title,artist,album,year) VALUES (13,'excepteurgreen','Catalina Horton','Joes New Jersey',2018);
INSERT INTO SONG(id,title,artist,album,year) VALUES (14,'mollitbrown','Oliver Patton','Garberville Minnesota',2013);
INSERT INTO SONG(id,title,artist,album,year) VALUES (15,'cillumblue','Frye Salinas','Thornport New York',2004);
INSERT INTO SONG(id,title,artist,album,year) VALUES (16,'idbrown','Butler Becker','Delwood Idaho',2011);
INSERT INTO SONG(id,title,artist,album,year) VALUES (17,'Lorembrown','Ladonna Mills','Snyderville American Samoa',1964);
INSERT INTO SONG(id,title,artist,album,year) VALUES (18,'deseruntblue','Bryan Dunn','Riner Colorado',2005);
INSERT INTO SONG(id,title,artist,album,year) VALUES (19,'sintblue','Camacho Miranda','Cutter Arizona',2021);
INSERT INTO SONG(id,title,artist,album,year) VALUES (20,'nostrudblue','Bernard Mcfadden','Englevale Kansas',1990);
INSERT INTO SONG(id,title,artist,album,year) VALUES (21,'deseruntblue','Ollie Guy','Juarez Delaware',1978);
INSERT INTO SONG(id,title,artist,album,year) VALUES (22,'temporblue','Marquita Pace','Cliff Nevada',2021);
INSERT INTO SONG(id,title,artist,album,year) VALUES (23,'minimgreen','Pate Austin','Vicksburg Iowa',1990);
INSERT INTO SONG(id,title,artist,album,year) VALUES (24,'nonbrown','Jewel Potts','Wadsworth Alabama',2022);
INSERT INTO SONG(id,title,artist,album,year) VALUES (25,'deseruntblue','Weiss Holloway','Nogal Michigan',1975);
INSERT INTO SONG(id,title,artist,album,year) VALUES (26,'excepteurbrown','Michael Poole','Disautel Wyoming',1996);
INSERT INTO SONG(id,title,artist,album,year) VALUES (27,'doloreblue','Leanne Merritt','Reno Utah',1979);
INSERT INTO SONG(id,title,artist,album,year) VALUES (28,'iruregreen','Blevins Mercer','Falmouth Palau',1965);
INSERT INTO SONG(id,title,artist,album,year) VALUES (29,'velitbrown','Cain Hooper','Norfolk Illinois',1986);
INSERT INTO SONG(id,title,artist,album,year) VALUES (30,'sintgreen','Rivers Fry','Crucible Florida',2011);
