-- initial songs
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (1,'dobrown','Lucy Parsons','Marion Marshall Islands',1973,'black');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (2,'consecteturbrown','Jennings Guerra','Kidder Nebraska',1966,'white');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (3,'eubrown','Hallie Hopkins','Sparkill Georgia',2000,'white');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (4,'voluptateblue','Ida Callahan','Alderpoint Indiana',1961,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (5,'aliquipgreen','Nadine Mooney','Statenville North Carolina',1976,'white');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (6,'eabrown','Mcmahon Petty','Biddle Massachusetts',1971,'white');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (7,'culpabrown','Becky Barber','Katonah Virginia',1987,'red');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (8,'suntblue','Yvette Hoover','Tonopah New Mexico',1979,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (9,'dolorebrown','Guadalupe Nieves','Thomasville California',2011,'black');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (10,'sitbrown','Alice Glover','Zortman Oklahoma',2015,'black');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (11,'voluptategreen','Esmeralda Armstrong','Maybell Washington',1971,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (12,'esseblue','Franklin Reid','Sandston Montana',1965,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (13,'excepteurgreen','Catalina Horton','Joes New Jersey',2018,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (14,'mollitbrown','Oliver Patton','Garberville Minnesota',2013,'white');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (15,'cillumblue','Frye Salinas','Thornport New York',2004,'white');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (16,'idbrown','Butler Becker','Delwood Idaho',2011,'black');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (17,'Lorembrown','Ladonna Mills','Snyderville American Samoa',1964,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (18,'deseruntblue','Bryan Dunn','Riner Colorado',2005,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (19,'sintblue','Camacho Miranda','Cutter Arizona',2021,'red');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (20,'nostrudblue','Bernard Mcfadden','Englevale Kansas',1990,'white');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (21,'deseruntblue','Ollie Guy','Juarez Delaware',1978,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (22,'temporblue','Marquita Pace','Cliff Nevada',2021,'black');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (23,'minimgreen','Pate Austin','Vicksburg Iowa',1990,'black');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (24,'nonbrown','Jewel Potts','Wadsworth Alabama',2022,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (25,'deseruntblue','Weiss Holloway','Nogal Michigan',1975,'black');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (26,'excepteurbrown','Michael Poole','Disautel Wyoming',1996,'black');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (27,'doloreblue','Leanne Merritt','Reno Utah',1979,'yellow');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (28,'iruregreen','Blevins Mercer','Falmouth Palau',1965,'red');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (29,'velitbrown','Cain Hooper','Norfolk Illinois',1986,'black');
INSERT INTO SONG(id,title,artist,album,year,category) VALUES (30,'sintgreen','Rivers Fry','Crucible Florida',2011,'white');
